runtime: java17
instance_class: F4 #F1  Different instance classes allow you to use different amounts of memory. F1 instance class is the smallest instance.

handlers:
  - url: /.*
    script: this field is required, but ignored
